env:
    TERM: xterm-256color

live_config_reload: true

background_opacity: 0.93

window:
    padding:
        x: 10
        y: 10

    title: Alacritty

    class:
        instance: Alacritty
        general: Alacritty
    
    dynamic_title: true

scrolling:
    history: 5000
    multiplier: 5

draw_bold_text_with_bright_colors: true

selection:
    semantic_escape_chars: ',│`|:"'' ()[]{}<>'
    save_to_clipboard: true

cursor:
    unfocused_hollow: true
    vi_mode_style: Block
