font:
    normal:
        family: "FiraCode Nerd Font"
        style: Regular
    bold:
        family: "FiraCode Nerd Font"
        style: Bold
    italic:
        family: "FiraCode Nerd Font"
        style: Italic
    bold_italic:
        family: "FiraCode Nerd Font"
        style: Bold Italic

    size: 12

    offset:
        x: 0
        y: 1

    glyph_offset:
        x: 0
        y: 0
