#!/bin/sh
path=$(pwd)

# ETC dir

# HOME dir

# CONFIG dir
[ -d $HOME/.config/bottom ] && rm -rf $HOME/.config/bottom
ln -sf $path/config/bottom  $HOME/.config/bottom
echo "> Bottom configurado correctamente"