#!/bin/sh
path=$(pwd)

# Home directory
ln -sf $path/.zshrc $HOME/.zshrc
ln -sf $path/.gtkrc-2.0 $HOME/.gtkrc-2.0

# .config directory
[ -d $HOME/.config/alacritty ] && rm -rf $HOME/.config/alacritty
ln -sf $path/.config/alacritty $HOME/.config/alacritty

[ -d $HOME/.config/bottom ] && rm -rf $HOME/.config/bottom
ln -sf $path/.config/bottom  $HOME/.config/bottom

[ -d $HOME/.config/bspwm ] && rm -rf $HOME/.config/bspwm
ln -sf $path/.config/bspwm $HOME/.config/bspwm

[ -d $HOME/.config/copyq ] && rm -rf $HOME/.config/copyq
ln -sf $path/.config/copyq $HOME/.config/copyq

[ -d $HOME/.config/dunst ] && rm -rf $HOME/.config/dunst
ln -sf $path/.config/dunst $HOME/.config/dunst

[ -d $HOME/.config/gtk-3.0 ] && rm -rf $HOME/.config/gtk-3.0
ln -sf $path/.config/gtk-3.0 $HOME/.config/gtk-3.0

[ -d $HOME/.config/mpv ] && rm -rf $HOME/.config/mpv
ln -s $path.config/mpv $HOME/.config/mpv

[ -d $HOME/.config/nvim ] && rm -rf $HOME/.config/nvim
ln -sf $path/.config/nvim $HOME/.config/nvim

[ -d $HOME/.config/picom ] && rm -rf $HOME/.config/picom
ln -sf $path/.config/picom $HOME/.config/picom

[ -d $HOME/.config/polybar ] && rm -rf $HOME/.config/polybar
ln -sf $path/.config/polybar $HOME/.config/polybar

[ -d $HOME/.config/rofi ] && rm -rf $HOME/.config/rofi
ln -sf $path/.config/rofi $HOME/.config/rofi

[ -d $HOME/.config/sxhkd ] && rm -rf $HOME/.config/sxhkd
ln -sf $path/.config/sxhkd $HOME/.config/sxhkd

[ -d $HOME/.config/zathura ] && rm -rf $HOME/.config/zathura
ln -sf $path/.config/zathura/ $HOME/.config/zathura

[ -d $HOME/.config/lf ] && rm -rf $HOME/.config/lf
ln -sf $path/.config/lf/ $HOME/.config/lf

# ln -sf $path/.config/lf/lf /home/dgloor/.local/bin/lf
# ln -sf $path/scripts/ $HOME/scripts/
