#!/bin/sh

preview() {
  cat <<-EOF | paste -sd '' >"$LF_UEBERZUG_TEMPDIR/fifo"
  {
  "action": "add", "identifier": "lf-preview",
  "path": "$1", "x": $4, "y": $5, "width": $2, "height": $3,
  "scaler": "contain"
}
EOF
}

batorcat() {
  file="$1"; shift
  if command -v bat >/dev/null 2>&1; then
    bat --color=always --style=plain --pager=never "$file" "$@"
  else
    cat "$file"
  fi
}

lf-ueberzug-cleaner # clean active preview

file="$1"; shift

case "$(basename "$file" | tr '[:upper:]' '[:lower:]')" in
  *.tgz | *.tar.gz) tar tzf "$file" ;;
  *.tar.bz2 | *.tbz2) tar tjf "$file" ;;
  *.tar.txz | *.txz) xz --list "$file" ;;
  *.tar) tar tf "$file" ;;
  *.zip | *.jar | *.war | *.ear | *.oxt) unzip -l "$file" ;;
  *.rar) unrar l "$file" ;;
  *.7z) 7z l "$file" ;;
  *.[1-8]) man "$file" | col -b ;;
  *.doc) catdoc "$file" ;;
  *.docx) docx2txt "$file" - ;;
  *.avi|*.mp4|*.mkv)
    thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
    ffmpeg -y -i "$file" -vframes 1 "$thumbnail"
    preview "$thumbnail" "$@"
    ;;
  *.pdf)
    thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
    gs -o "$thumbnail" -sDEVICE=pngalpha -dLastPage=1 "$file" >/dev/null
    preview "$thumbnail" "$@"
    ;;
  *.jpg|*.jpeg|*.png|*.bmp)
    preview "$file" "$@" ;;
  *.svg)
    thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
    gm convert "$file" "$thumbnail"
    preview "$thumbnail" "$@"
    ;;
  *.gif)
    thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
    gm convert "$file[0]" "$thumbnail"
    preview "$thumbnail" "$@"
    ;;
  *) batorcat "$file" ;;
esac

return 127 # nonzero retcode required for lf previews to reload
