let g:coc_global_extensions = [
    \ 'coc-clangd',
    \ 'coc-css',
    \ 'coc-emmet',
    \ 'coc-eslint',
    \ 'coc-html',
    \ 'coc-json',
    \ 'coc-lua',
    \ 'coc-marketplace',
    \ 'coc-prettier',
    \ 'coc-python',
    \ 'coc-svg',
    \ 'coc-vimlsp',
    \ 'coc-xml',
    \ ]
