#!/bin/sh

bspc rule -r "*"

# ========== AutoStart  ========== #
setxkbmap latam &
numlockx &
xset r rate 200 30 &
unclutter --timeout 3 &

xwallpaper --zoom ~/.config/wall.jpg &
picom &
copyq &
#udiskie &
#nm-applet &

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || ~/.scripts/polybar/launchpolybar &
pgrep ~/.scripts/bspwm/bspwm-swallow || ~/.scripts/bspwm/bspwm-swallow &


# ========== Monitors  ========== #
bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9


# ========== Global Settings  ========== #
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus button1

bspc config merge_overlapping_monitors true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

bspc config single_monocle true
bspc config gapless_monocle true
bspc config top_monocle_padding 15
bspc config right_monocle_padding 15
bspc config left_monocle_padding 15
bspc config bottom_monocle_padding 15

bspc config normal_border_color "#44475A"
bspc config active_border_color "#6272A4"
bspc config focused_border_color "#6272A4"
bspc config presel_feedback_color "#6272A4"
# bspc config focused_border_color "#ff79c6"
# bspc config active_border_color "#bd93f9"

# wmname LG3D & # fix for some Java apps


# ========== Monitor and Desktop Settings  ========== #
bspc config window_gap 0
bspc config border_width 1
# bspc config top_padding 30
# bspc config bottom_padding 5
# bspc config left_padding 5
# bspc config right_padding 5


# ========== Rules ========== #
bspc rule -a copyq state=floating
bspc rule -a zoom state=tiled
bspc rule -a obs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a balena-etcher state=tiled
bspc rule -a OpenBoard state=tiled
bspc rule -a app.App state=floating
bspc rule -a matplotlib state=floating
bspc rule -a Droidcam state=tiled
bspc rule -a Com.github.ronnydo.colorpicker state=tiled
# bspc rule -a mpv state=fullscreen
# bspc rule -a Gnome-pomodoro state=floating
# bspc rule -a Anki state=fullscreen
