#!/bin/sh
# Open a basic yes/no prompt with rofi
# Useful for confirming whether an action should be taken

if [ $(echo "Yes|No" | rofi -dmenu -i -width 30 -lines 2 -p "$1" -sep '|') == "Yes" ]; then
  $2
fi
