#!/bin/sh

# Set the selected x keyboard layout

_rofi() {
    rofi \
        -dmenu \
        -i \
        -width 30 \
        -lines $lines \
        -no-custom true \
        -disable-history true \
        -p "Keys" \
        -sep '|' \
        "$@"
}

options="latam|dvorak|it"

lines="$(awk -F '|' '{print NF}' <<< "$options")"
choice=$(echo "$options" | _rofi)

setxkbmap $choice
