#!/bin/sh

_rofi() {
    rofi \
        -dmenu \
        -i \
        -width 30 \
        -lines 4 \
        -no-custom true \
        -disable-history true \
        -p "Power" \
        -sep '|' \
        "$@"
}

OPTIONS="Restart|Log out|Suspend|Power off"
ENTRY=$(echo "$OPTIONS" | _rofi)

if [ "$ENTRY" = "Restart" ]; then
    $TERMINAL -e sudo reboot

elif [ "$ENTRY" = "Log out" ]; then
    bspc quit

elif [ "$ENTRY" = "Suspend" ]; then
    $TERMINAL -e systemctl suspend

elif [ "$ENTRY" = "Power off" ]; then
    $TERMINAL -e sudo poweroff

else
    echo "err"
fi
