#!/bin/sh

_rofi() {
    rofi \
        -dmenu \
        -i \
        -width 30 \
        -lines 4 \
        -no-custom true \
        -disable-history true \
        -p "Power" \
        -sep '|' \
        "$@"
}

options="Restart|Log out|Suspend|Shutdown"
choice=$(echo "$options" | _rofi)

if [ "$choice" = "Restart" ]; then
    $TERMINAL -e sudo reboot

elif [ "$choice" = "Log out" ]; then
    bspc quit

elif [ "$choice" = "Suspend" ]; then
    $TERMINAL -e systemctl suspend

elif [ "$choice" = "Shutdown" ]; then
    $TERMINAL -e sudo poweroff

else
    echo "err"
fi
