#!/bin/sh
# Simple script for toggle window gap in bspwm

g=`bspc config window_gap `
if [ $g = 0 ];then  
  bspc config top_padding 25
  bspc config bottom_padding 15
  bspc config left_padding 15
  bspc config right_padding 15
  bspc config window_gap 10
else
  bspc config top_padding 25
  bspc config bottom_padding 0
  bspc config left_padding 0
  bspc config right_padding 0
  bspc config window_gap 0
fi
