#!/bin/sh 

# Increase or decrease bspwm gaps by 1.

current_gap=$(expr $(bspc config window_gap))

if [ $1 = "increase" ]; then
  bspc config window_gap $(expr $current_gap + 1)
elif [ $1 = "decrease" ]; then
  if [ ${current_gap} != 0 ]; then
    bspc config window_gap $(expr $current_gap - 1)
  else 
    echo "What are you trying to do? D:"
  fi
else
  echo "Wrong argument!"
  exit 1
fi

exit 0
