
# Don't print a new line at the start of the prompt
add_newline = false

# Separates the prompt into two lines.
[line_break]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[nodejs]
disabled = true

[java]
disabled = true

[golang]
disabled = true
