
add_newline = false

[line_break]
disabled = true

# Replace the "❯" symbol in the prompt
# [character]
# success_symbol = "[➜ ](green)"
# error_symbol = "[➜ ](red)"

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true
