#!/bin/sh

bspc rule -r "*" 

###---Autostart---###
pgrep -x sxhkd > /dev/null || sxhkd &

# Bar 
~/scripts/polybar/launchpolybar &

# Wallpaper
xwallpaper --stretch ~/dotfiles/wallpapers/0047.jpg &

# Num lock

numlockx &
# Nofications

dunst &
# Typematic Delay
xset r rate 200 30 &

# Compositor
picom &

# Systray 
copyq & 
# nm-applet & 

# Dwm swallow feature :D
pgrep ~/scripts/bspwm/bspwm-swallow || ~/scripts/bspwm/bspwm-swallow &


###---MONITORS---###
bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"#1e1e1e"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color	"#5e81ac"

###---Monitor And Desktop Settings----###
bspc config top_padding 20
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

###---Rules---###
# bspc rule -a 'Apache NetBeans IDE 11.0' state=tiled
bspc rule -a mpv state=fullscreen
bspc rule -a zoom state=tiled
bspc rule -a com.github.ronnydo.colorpicker state=tiled
bspc rule -a obs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a guvcview state=floating rectangle=480x270+1440+810 sticky=on layer=above
