#!/bin/sh

bspc rule -r "*" 

###---Autostart---###
pgrep -x sxhkd > /dev/null || sxhkd &

# Wallpaper
xwallpaper --stretch ~/dotfiles/wallpapers/0047.jpg &

# Num lock

numlockx &
# Nofications

dunst &
# Typematic Delay
xset r rate 200 30 &

# Compositor
picom &

# Bar 
~/scripts/polybar/launchpolybar &

# Systray 
copyq & 
# nm-applet & 

# Dwm swallow feature :D
pgrep ~/scripts/bspwm/bspwm-swallow || ~/scripts/bspwm/bspwm-swallow &


###---MONITORS---###
bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9


###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"#1e1e1e"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#0f5171"
bspc config presel_feedback_color	"#282c34"


wmname LG3D & # fix for some Java apps


###---Monitor And Desktop Settings----###
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 5


####---Rules---###
#bspc rule -a mpv state=fullscreen
bspc rule -a copyq state=floating
bspc rule -a zoom state=tiled
bspc rule -a obs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a com.github.ronnydo.colorpicker state=floating
bspc rule -a balena-etcher state=tiled
bspc rule -a OpenBoard state=tiled
bspc rule -a wpp state=tiled
# bspc rule -a com.mycompany.expression_tree.App state=floating
